### ISSUE TITLE
能不能添加win平台下的编译文档

### ISSUE THREAD

**Issue by thrt520asd** [larryhou/MemoryProfiler#4]
如题

**Comment by larryhou** [comment]
已经在适配了，这个项目基本是业余时间来做的，要晚点才能支持

**Comment by laisiyu** [comment]
妈呀我真服了，我没看到微信好友请求然后已经过期了，我点开一手滑把它给删了？？？然后我找了一圈没找到你微信号我他妈在github上找到你了可太不容易了吧sss

**Comment by thrt520asd** [comment]
大佬辛苦  雷锋精神永不灭

**Comment by laisiyu** [comment]
sb

**Comment by larryhou** [comment]
可以参考@pluswu的[pr](https://github.com/larryhou/MemoryProfiler/pull/5)，里面实现了用`cygwin`编译；也可以参考@yangruihan的[pr](https://github.com/larryhou/MemoryProfiler/pull/1)，实现了用`VS`编译
